### ISSUE TITLE
A debug class ?

### ISSUE THREAD

**Issue by nuxlight** [hzeller/precise-pitch#1]
Hi hzeller,

I working on your application to add some features and a french traduction :)
I have just a question for debuging the app : 
Did you make a class to test the practice activity or you had test this every time with the cello ? 
You had make a DebugPitchSource class but i don't understand his fonctionnement :/

Thanks for your help.

**Comment by hzeller** [comment]
The DebugPitchSource is enabled if you set `isAutoFollow` true in the `NoteFollowRecorder` class. With that, it is possible to simulate going through the notes without having to play them.

What it does is to implement a PitchSource (whereas the normal implementation is the one listening on the microphone) - but this is geting a frequency it should generate (`setExpectedPitch()`), and then simulates it with some artificial random jitter.

**Comment by nuxlight** [comment]
Perfect, thanks a lot :)
